<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Output;

use Automattic\WooCommerce\Api\Infrastructure\ResolverHelpers;
use Automattic\WooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\WooCommerce\Api\Infrastructure\Schema\Type;

class Attendee {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'          => 'Attendee',
					'description'   => __( 'A registration for an event.', 'woocommerce' ),
					'authorization' => array(
						array(
							'attribute' => 'RequiresScope',
							'args'      => array(
								0 => 'events:read',
							),
						),
					),
					'fields'        => fn() => array(
						'id'          => array(
							'type'          => Type::int(),
							'description'   => __( 'Numeric identifier.', 'woocommerce' ),
							'authorization' => array(
								array(
									'attribute' => 'RequiresScope',
									'args'      => array(
										0 => 'events:read',
									),
								),
							),
							'resolve'       => function ( $parent, $args, $context ) {
							$principal = $context['principal'];
							$_metadata = array(
								'query' => $context['_query_metadata'] ?? array(),
								'type'  => array(),
								'field' => array(),
							);
							$_args     = $args;
							$_parent   = $parent;
							if ( ! ( ( new \Automattic\WooCommerceSimpleEvents\Api\Attributes\RequiresScope( 'events:read' ) )->authorize( $principal ) ) ) {
								throw ResolverHelpers::build_field_authorization_error( $principal, 'Attendee', 'id', 'RequiresScope' );
							}
															return $parent->id;
						},
						),
						'event_id'    => array(
							'type'          => Type::int(),
							'description'   => __( 'Identifier of the event this attendee registered for.', 'woocommerce' ),
							'authorization' => array(
								array(
									'attribute' => 'RequiresScope',
									'args'      => array(
										0 => 'events:read',
									),
								),
							),
							'resolve'       => function ( $parent, $args, $context ) {
							$principal = $context['principal'];
							$_metadata = array(
								'query' => $context['_query_metadata'] ?? array(),
								'type'  => array(),
								'field' => array(),
							);
							$_args     = $args;
							$_parent   = $parent;
							if ( ! ( ( new \Automattic\WooCommerceSimpleEvents\Api\Attributes\RequiresScope( 'events:read' ) )->authorize( $principal ) ) ) {
								throw ResolverHelpers::build_field_authorization_error( $principal, 'Attendee', 'event_id', 'RequiresScope' );
							}
															return $parent->event_id;
						},
						),
						'name'        => array(
							'type'          => Type::string(),
							'description'   => __( 'Attendee name as captured during registration.', 'woocommerce' ),
							'authorization' => array(
								array(
									'attribute' => 'RequiresScope',
									'args'      => array(
										0 => 'attendees:read_pii',
									),
								),
								array(
									'attribute' => 'RequiresScope',
									'args'      => array(
										0 => 'events:read',
									),
								),
							),
							'resolve'       => function ( $parent, $args, $context ) {
							$principal = $context['principal'];
							$_metadata = array(
								'query' => $context['_query_metadata'] ?? array(),
								'type'  => array(),
								'field' => array(),
							);
							$_args     = $args;
							$_parent   = $parent;
							if ( ! ( ( new \Automattic\WooCommerceSimpleEvents\Api\Attributes\RequiresScope( 'attendees:read_pii' ) )->authorize( $principal ) && ( new \Automattic\WooCommerceSimpleEvents\Api\Attributes\RequiresScope( 'events:read' ) )->authorize( $principal ) ) ) {
								throw ResolverHelpers::build_field_authorization_error( $principal, 'Attendee', 'name', 'RequiresScope' );
							}
															return $parent->name;
						},
						),
						'email'       => array(
							'type'          => Type::string(),
							'description'   => __( 'Attendee email captured during registration.', 'woocommerce' ),
							'authorization' => array(
								array(
									'attribute' => 'RequiresScope',
									'args'      => array(
										0 => 'attendees:read_pii',
									),
								),
								array(
									'attribute' => 'RequiresScope',
									'args'      => array(
										0 => 'events:read',
									),
								),
							),
							'resolve'       => function ( $parent, $args, $context ) {
							$principal = $context['principal'];
							$_metadata = array(
								'query' => $context['_query_metadata'] ?? array(),
								'type'  => array(),
								'field' => array(),
							);
							$_args     = $args;
							$_parent   = $parent;
							if ( ! ( ( new \Automattic\WooCommerceSimpleEvents\Api\Attributes\RequiresScope( 'attendees:read_pii' ) )->authorize( $principal ) && ( new \Automattic\WooCommerceSimpleEvents\Api\Attributes\RequiresScope( 'events:read' ) )->authorize( $principal ) ) ) {
								throw ResolverHelpers::build_field_authorization_error( $principal, 'Attendee', 'email', 'RequiresScope' );
							}
															return $parent->email;
						},
						),
						'paid_amount' => array(
							'type'          => Type::float(),
							'description'   => __( 'Amount the attendee paid for their ticket.', 'woocommerce' ),
							'authorization' => array(
								array(
									'attribute' => 'RequiresScope',
									'args'      => array(
										0 => 'attendees:payment',
									),
								),
								array(
									'attribute' => 'RequiresScope',
									'args'      => array(
										0 => 'events:read',
									),
								),
							),
							'resolve'       => function ( $parent, $args, $context ) {
							$principal = $context['principal'];
							$_metadata = array(
								'query' => $context['_query_metadata'] ?? array(),
								'type'  => array(),
								'field' => array(),
							);
							$_args     = $args;
							$_parent   = $parent;
							if ( ! ( ( new \Automattic\WooCommerceSimpleEvents\Api\Attributes\RequiresScope( 'attendees:payment' ) )->authorize( $principal ) && ( new \Automattic\WooCommerceSimpleEvents\Api\Attributes\RequiresScope( 'events:read' ) )->authorize( $principal ) ) ) {
								throw ResolverHelpers::build_field_authorization_error( $principal, 'Attendee', 'paid_amount', 'RequiresScope' );
							}
															return $parent->paid_amount;
						},
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
