<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Output;

use Automattic\WooCommerce\Api\Infrastructure\ResolverHelpers;
use Automattic\WooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\WooCommerce\Api\Infrastructure\Schema\Type;

class EventStats {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'          => 'EventStats',
					'description'   => __( 'Aggregate statistics for an event.', 'woocommerce' ),
					'authorization' => array(
						array(
							'attribute' => 'RequiresScope',
							'args'      => array(
								0 => 'events:read',
							),
						),
					),
					'fields'        => fn() => array(
						'event_id'             => array(
							'type'          => Type::int(),
							'description'   => __( 'Identifier of the event the statistics summarise.', 'woocommerce' ),
							'authorization' => array(
								array(
									'attribute' => 'RequiresScope',
									'args'      => array(
										0 => 'events:read',
									),
								),
							),
							'resolve'       => function ( $parent, $args, $context ) {
							$principal = $context['principal'];
							$_metadata = array(
								'query' => $context['_query_metadata'] ?? array(),
								'type'  => array(),
								'field' => array(),
							);
							$_args     = $args;
							$_parent   = $parent;
							if ( ! ( ( new \Automattic\WooCommerceSimpleEvents\Api\Attributes\RequiresScope( 'events:read' ) )->authorize( $principal ) ) ) {
								throw ResolverHelpers::build_field_authorization_error( $principal, 'EventStats', 'event_id', 'RequiresScope' );
							}
															return $parent->event_id;
						},
						),
						'attendees_total'      => array(
							'type'          => Type::int(),
							'description'   => __( 'Total number of registered attendees.', 'woocommerce' ),
							'authorization' => array(
								array(
									'attribute' => 'RequiresScope',
									'args'      => array(
										0 => 'events:read',
									),
								),
							),
							'resolve'       => function ( $parent, $args, $context ) {
							$principal = $context['principal'];
							$_metadata = array(
								'query' => $context['_query_metadata'] ?? array(),
								'type'  => array(),
								'field' => array(),
							);
							$_args     = $args;
							$_parent   = $parent;
							if ( ! ( ( new \Automattic\WooCommerceSimpleEvents\Api\Attributes\RequiresScope( 'events:read' ) )->authorize( $principal ) ) ) {
								throw ResolverHelpers::build_field_authorization_error( $principal, 'EventStats', 'attendees_total', 'RequiresScope' );
							}
															return $parent->attendees_total;
						},
						),
						'revenue_total'        => array(
							'type'          => Type::float(),
							'description'   => __( 'Total revenue collected from registrations.', 'woocommerce' ),
							'authorization' => array(
								array(
									'attribute' => 'RequiresScope',
									'args'      => array(
										0 => 'events:revenue',
									),
								),
								array(
									'attribute' => 'RequiresScope',
									'args'      => array(
										0 => 'events:read',
									),
								),
							),
							'resolve'       => function ( $parent, $args, $context ) {
							$principal = $context['principal'];
							$_metadata = array(
								'query' => $context['_query_metadata'] ?? array(),
								'type'  => array(),
								'field' => array(),
							);
							$_args     = $args;
							$_parent   = $parent;
							if ( ! ( ( new \Automattic\WooCommerceSimpleEvents\Api\Attributes\RequiresScope( 'events:revenue' ) )->authorize( $principal ) && ( new \Automattic\WooCommerceSimpleEvents\Api\Attributes\RequiresScope( 'events:read' ) )->authorize( $principal ) ) ) {
								throw ResolverHelpers::build_field_authorization_error( $principal, 'EventStats', 'revenue_total', 'RequiresScope' );
							}
															return $parent->revenue_total;
						},
						),
						'paid_attendees_count' => array(
							'type'          => Type::int(),
							'description'   => __( 'Number of attendees whose paid_amount is greater than zero.', 'woocommerce' ),
							'authorization' => array(
								array(
									'attribute' => 'RequiresScope',
									'args'      => array(
										0 => 'attendees:payment',
									),
								),
								array(
									'attribute' => 'RequiresScope',
									'args'      => array(
										0 => 'events:read',
									),
								),
							),
							'resolve'       => function ( $parent, $args, $context ) {
							$principal = $context['principal'];
							$_metadata = array(
								'query' => $context['_query_metadata'] ?? array(),
								'type'  => array(),
								'field' => array(),
							);
							$_args     = $args;
							$_parent   = $parent;
							if ( ! ( ( new \Automattic\WooCommerceSimpleEvents\Api\Attributes\RequiresScope( 'attendees:payment' ) )->authorize( $principal ) && ( new \Automattic\WooCommerceSimpleEvents\Api\Attributes\RequiresScope( 'events:read' ) )->authorize( $principal ) ) ) {
								throw ResolverHelpers::build_field_authorization_error( $principal, 'EventStats', 'paid_attendees_count', 'RequiresScope' );
							}
															return $parent->paid_attendees_count;
						},
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
