<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Output;

use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Enums\EventStatus as EventStatusType;
use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Output\Session;
use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Scalars\DateTime as DateTimeType;
use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Interfaces\ScheduledItem as ScheduledItemInterface;
use Automattic\WooCommerce\Api\Infrastructure\ResolverHelpers;
use Automattic\WooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\WooCommerce\Api\Infrastructure\Schema\Type;

class Event {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'        => 'Event',
					'description' => __( 'An event open for registration.', 'woocommerce-simple-events' ),
					'interfaces'  => fn() => array(
						ScheduledItemInterface::get(),
					),
					'fields'      => fn() => array(
						'name'            => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'Human-readable name.', 'woocommerce-simple-events' ),
						),
						'description'     => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'Detailed description shown on the public event page.', 'woocommerce-simple-events' ),
						),
						'status'          => array(
							'type'        => Type::nonNull( EventStatusType::get() ),
							'description' => __( 'Current lifecycle status.', 'woocommerce-simple-events' ),
						),
						'raw_status'      => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'Raw status string as stored. Useful when status is OTHER.', 'woocommerce-simple-events' ),
						),
						'venue'           => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'Venue (free-form text).', 'woocommerce-simple-events' ),
						),
						'location'        => array(
							'type'              => Type::nonNull( Type::string() ),
							'description'       => __( 'Where the event takes place.', 'woocommerce-simple-events' ),
							'deprecationReason' => 'Use venue instead.',
						),
						'capacity'        => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'Maximum number of attendees the venue can accept.', 'woocommerce-simple-events' ),
						),
						'sessions'        => array(
							'type'        => Type::nonNull( Type::listOf( Type::nonNull( Session::get() ) ) ),
							'description' => __( 'Talks scheduled for this event.', 'woocommerce-simple-events' ),
						),
						'organizer_login' => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'Login of the user who created the event.', 'woocommerce-simple-events' ),
						),
						'sequence'        => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( '[Internal] Internal sort order.', 'woocommerce-simple-events' ),
							'metadata'    => array(
								'internal' => true,
							),
						),
						'waitlist_size'   => array(
							'type'          => Type::nonNull( Type::int() ),
							'description'   => __( 'Number of people on the waitlist for this event.', 'woocommerce-simple-events' ),
							'authorization' => array(
								array(
									'attribute' => 'OwnerOrScope',
									'args'      => array(
										0 => 'events:waitlist',
									),
								),
							),
							'resolve'       => function ( $parent, $args, $context ) {
							$principal = $context['principal'];
							$_metadata = array(
								'query' => $context['_query_metadata'] ?? array(),
								'type'  => array(),
								'field' => array(),
							);
							$_args     = $args;
							$_parent   = $parent;
							if ( ! ( ( new \Automattic\WooCommerceSimpleEvents\Api\Attributes\OwnerOrScope( 'events:waitlist' ) )->authorize( $principal, _parent: $_parent ) ) ) {
								throw ResolverHelpers::build_field_authorization_error( $principal, 'Event', 'waitlist_size', 'OwnerOrScope' );
							}
															return $parent->waitlist_size;
						},
						),
						'revenue'         => array(
							'type'          => Type::float(),
							'description'   => __( 'Total revenue collected from registrations for this event.', 'woocommerce-simple-events' ),
							'authorization' => array(
								array(
									'attribute' => 'RequiresScope',
									'args'      => array(
										0 => 'events:revenue',
									),
								),
							),
							'resolve'       => function ( $parent, $args, $context ) {
							$principal = $context['principal'];
							$_metadata = array(
								'query' => $context['_query_metadata'] ?? array(),
								'type'  => array(),
								'field' => array(),
							);
							$_args     = $args;
							$_parent   = $parent;
							if ( ! ( ( new \Automattic\WooCommerceSimpleEvents\Api\Attributes\RequiresScope( 'events:revenue' ) )->authorize( $principal ) ) ) {
								throw ResolverHelpers::build_field_authorization_error( $principal, 'Event', 'revenue', 'RequiresScope' );
							}
															return $parent->revenue;
						},
						),
						'internal_notes'  => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'Free-form notes used internally by event managers.', 'woocommerce-simple-events' ),
							'resolve'     => function ( $parent, $args, $context ) {
							$principal = $context['principal'];
							$_metadata = array(
								'query' => $context['_query_metadata'] ?? array(),
								'type'  => array(),
								'field' => array(),
							);
							$_args     = $args;
							$_parent   = $parent;
							if ( ! ( ( new \Automattic\WooCommerceSimpleEvents\Api\Attributes\RequiresScope( 'events:internal_notes' ) )->authorize( $principal ) ) ) {
								throw ResolverHelpers::build_field_authorization_error( $principal, 'Event', 'internal_notes', 'RequiresScope' );
							}
															return $parent->internal_notes;
						},
						),
						'id'              => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'Numeric identifier.', 'woocommerce-simple-events' ),
						),
						'date'            => array(
							'type'        => DateTimeType::get(),
							'description' => __( 'Date and time the item occurs, as an ISO 8601 string.', 'woocommerce-simple-events' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
