<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Output;

use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Scalars\DateTime as DateTimeType;
use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Interfaces\ScheduledItem as ScheduledItemInterface;
use Automattic\WooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\WooCommerce\Api\Infrastructure\Schema\Type;

class Session {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'        => 'Session',
					'description' => __( 'A talk or session in an event programme.', 'woocommerce-simple-events' ),
					'metadata'    => array(
						'team' => 'events-platform',
					),
					'interfaces'  => fn() => array(
						ScheduledItemInterface::get(),
					),
					'fields'      => fn() => array(
						'title'   => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'Session title.', 'woocommerce-simple-events' ),
						),
						'speaker' => array(
							'type'        => Type::string(),
							'description' => __( 'Name of the speaker, if announced.', 'woocommerce-simple-events' ),
						),
						'id'      => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'Numeric identifier.', 'woocommerce-simple-events' ),
						),
						'date'    => array(
							'type'        => DateTimeType::get(),
							'description' => __( 'Date and time the item occurs, as an ISO 8601 string.', 'woocommerce-simple-events' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
