<?php

declare(strict_types=1);

namespace Automattic\WooCommerceSimpleEvents\Api\Infrastructure;

/**
 * Class resolver for this plugin's code-API command classes.
 *
 * ApiBuilder detects any class at
 * `<plugin-api-namespace>\Infrastructure\ClassResolver` with a public static
 * `resolve_class(string): object` method and routes every autogenerated
 * resolver's command lookup through it. Trivial `new` is enough for the
 * demo; a real plugin would delegate to its container.
 */
class ClassResolver {
	/**
	 * @param class-string $class_name
	 */
	public static function resolve_class( string $class_name ): object {
		return new $class_name();
	}
}
