<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLQueries;

use Automattic\WooCommerceSimpleEvents\Api\Queries\ListAttendees as ListAttendeesCommand;
use Automattic\WooCommerce\Api\Infrastructure\QueryInfoExtractor;
use Automattic\WooCommerce\Api\Infrastructure\ResolverHelpers;
use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Output\Attendee;
use Automattic\WooCommerce\Api\Infrastructure\Schema\ResolveInfo;
use Automattic\WooCommerce\Api\Infrastructure\Schema\Type;

class ListAttendees {
	public static function get_field_definition(): array {
		return array(
			'type'          => Type::nonNull( Type::listOf( Type::nonNull( Attendee::get() ) ) ),
			'description'   => __( 'List attendees for an event.', 'woocommerce-simple-events' ),
			'authorization' => array(
				array(
					'attribute' => 'PublicAccess',
					'args'      => array(),
				),
			),
			'args'          => array(
				'event_id' => array(
					'type'        => Type::nonNull( Type::int() ),
					'description' => __( 'Identifier of the event whose attendees to list.', 'woocommerce-simple-events' ),
				),
			),
			'resolve'       => array( self::class, 'resolve' ),
		);
	}

	public static function resolve( mixed $root, array $args, mixed $context, ResolveInfo $info ): mixed {
		// Publish the root query's metadata so downstream field-level
		// authorization gates can read it via `$_metadata['query']`.
		// $context is an ArrayObject (see GraphQLController::process_request())
		// so the mutation propagates to nested resolvers.
		$context['_query_metadata'] = array();

		$command = \Automattic\WooCommerceSimpleEvents\Api\Infrastructure\ClassResolver::resolve_class( ListAttendeesCommand::class );

		$execute_args = array();
		if ( array_key_exists( 'event_id', $args ) ) {
			$execute_args['event_id'] = $args['event_id'];
		}

		$result = ResolverHelpers::execute_command( $command, $execute_args );

		return $result;
	}

	/**
	 * Compute the value `_preauthorized` would carry for a given principal —
	 * the AND of the autodiscovered authorization attributes' authorize()
	 * outcomes on this command. Single source of truth for both the resolver's
	 * own gates and external (code-API) callers asking about authorization
	 * without going through GraphQL execution.
	 *
	 * Returns true vacuously when the command has no authorization attributes
	 * (in that case authorize() on the command is the sole guard, and that
	 * method should be consulted instead).
	 */
	public static function compute_preauthorized( \Automattic\WooCommerceSimpleEvents\Api\Infrastructure\EventsPrincipal $principal ): bool {
		return true;
	}
}
