<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Input;

use Automattic\WooCommerce\Api\Infrastructure\Schema\InputObjectType;
use Automattic\WooCommerce\Api\Infrastructure\Schema\Type;

class Registration {
	private static ?InputObjectType $instance = null;

	public static function get(): InputObjectType {
		if ( null === self::$instance ) {
			self::$instance = new InputObjectType(
				array(
					'name'        => 'RegistrationInput',
					'description' => __( 'Data submitted to register an attendee for an event.', 'woocommerce-simple-events' ),
					'fields'      => fn() => array(
						'event_id'       => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'Identifier of the event being registered for.', 'woocommerce-simple-events' ),
						),
						'attendee_name'  => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'Attendee name.', 'woocommerce-simple-events' ),
						),
						'attendee_email' => array(
							'type'        => Type::nonNull( Type::string() ),
							'description' => __( 'Attendee email.', 'woocommerce-simple-events' ),
						),
						'paid_amount'    => array(
							'type'        => Type::float(),
							'description' => __( 'Amount the attendee paid; only finance staff may set this on creation.', 'woocommerce-simple-events' ),
						),
						'internal_notes' => array(
							'type'        => Type::string(),
							'description' => __( 'Internal notes attached to the registration; only managers may set them.', 'woocommerce-simple-events' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
