<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Input;

use Automattic\WooCommerce\Api\Infrastructure\Schema\InputObjectType;
use Automattic\WooCommerce\Api\Infrastructure\Schema\Type;

class UpdateEvent {
	private static ?InputObjectType $instance = null;

	public static function get(): InputObjectType {
		if ( null === self::$instance ) {
			self::$instance = new InputObjectType(
				array(
					'name'          => 'UpdateEventInput',
					'description'   => __( 'Patchable fields on an event.', 'woocommerce-simple-events' ),
					'authorization' => array(
						array(
							'attribute' => 'RequiresScope',
							'args'      => array(
								0 => 'events:edit',
							),
						),
					),
					'fields'        => fn() => array(
						'name'           => array(
							'type'        => Type::string(),
							'description' => __( 'New event name.', 'woocommerce-simple-events' ),
						),
						'capacity'       => array(
							'type'        => Type::int(),
							'description' => __( 'New capacity for the venue.', 'woocommerce-simple-events' ),
						),
						'waitlist_size'  => array(
							'type'        => Type::int(),
							'description' => __( 'New waitlist size.', 'woocommerce-simple-events' ),
						),
						'internal_notes' => array(
							'type'        => Type::string(),
							'description' => __( 'Replacement internal notes.', 'woocommerce-simple-events' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
