<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Enums;

use Automattic\WooCommerceSimpleEvents\Api\Enums\EventStatus as EventStatusEnum;
use Automattic\WooCommerce\Api\Infrastructure\Schema\EnumType;

class EventStatus {
	private static ?EnumType $instance = null;

	public static function get(): EnumType {
		if ( null === self::$instance ) {
			self::$instance = new EnumType(
				array(
					'name'        => 'EventStatus',
					'description' => __( 'The lifecycle status of an event.', 'woocommerce-simple-events' ),
					'values'      => array(
						'DRAFT'     => array(
							'value'       => EventStatusEnum::Draft,
							'description' => __( 'Created but not yet open for registration.', 'woocommerce-simple-events' ),
						),
						'PUBLISHED' => array(
							'value'       => EventStatusEnum::Published,
							'description' => __( 'Open for registration.', 'woocommerce-simple-events' ),
						),
						'CANCELLED' => array(
							'value'       => EventStatusEnum::Cancelled,
							'description' => __( 'Called off; no further registrations are accepted.', 'woocommerce-simple-events' ),
						),
						'COMPLETED' => array(
							'value'       => EventStatusEnum::Completed,
							'description' => __( 'Already took place.', 'woocommerce-simple-events' ),
						),
						'OTHER'     => array(
							'value'       => EventStatusEnum::Other,
							'description' => __( 'A status not covered by the standard values. Inspect raw_status for the underlying value.', 'woocommerce-simple-events' ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
