<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated;

use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLQueries\GetStatistics;
use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLQueries\ListEventsConnection;
use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLQueries\GetEvent;
use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLQueries\ListAttendees;
use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLQueries\ListEvents;
use Automattic\WooCommerce\Api\Infrastructure\MetadataController;
use Automattic\WooCommerce\Api\Infrastructure\Schema\ObjectType;

class RootQueryType {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'   => 'Query',
					'fields' => fn() => array(
						'statistics'                   => GetStatistics::get_field_definition(),
						'eventsConnection'             => ListEventsConnection::get_field_definition(),
						'event'                        => GetEvent::get_field_definition(),
						'attendees'                    => ListAttendees::get_field_definition(),
						'events'                       => ListEvents::get_field_definition(),
						MetadataController::FIELD_NAME => MetadataController::get_field_definition(),
					),
				)
			);
		}
		return self::$instance;
	}
}
