<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated;

use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLMutations\DeleteEvent;
use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLMutations\UpdateEvent;
use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLMutations\RegisterForEvent;
use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLMutations\CancelEvent;
use Automattic\WooCommerce\Api\Infrastructure\Schema\ObjectType;

class RootMutationType {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'   => 'Mutation',
					'fields' => fn() => array(
						'deleteEvent'      => DeleteEvent::get_field_definition(),
						'updateEvent'      => UpdateEvent::get_field_definition(),
						'registerForEvent' => RegisterForEvent::get_field_definition(),
						'cancelEvent'      => CancelEvent::get_field_definition(),
					),
				)
			);
		}
		return self::$instance;
	}
}
