<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated;

use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Output\Event;
use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Output\Session;

class TypeRegistry {
	/**
	 * Return all concrete types that implement interfaces.
	 *
	 * Pass this to the Schema 'types' config so that inline fragments
	 * (e.g. `... on VariableProduct`) are resolvable.
	 *
	 * @return array
	 */
	public static function get_interface_implementors(): array {
		return array(
			Event::get(),
			Session::get(),
		);
	}
}
