<?php

declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Pagination;

use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Output\Event as EventType;
use Automattic\WooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\WooCommerce\Api\Infrastructure\Schema\Type;

class EventConnection {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'        => 'EventConnection',
					'description' => __( 'A connection to a list of Event items.', 'woocommerce-simple-events' ),
					'fields'      => fn() => array(
						'edges'       => array(
							'type' => Type::nonNull(
								Type::listOf(
									Type::nonNull(
										EventEdge::get()
									)
								)
							),
						),
						'nodes'       => array(
							'type' => Type::nonNull(
								Type::listOf(
									Type::nonNull(
										EventType::get()
									)
								)
							),
						),
						'page_info'   => array(
							'type' => Type::nonNull( PageInfo::get() ),
						),
						'total_count' => array(
							'type' => Type::nonNull( Type::int() ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
