<?php

declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Pagination;

use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Output\Event as EventType;
use Automattic\WooCommerce\Api\Infrastructure\Schema\ObjectType;
use Automattic\WooCommerce\Api\Infrastructure\Schema\Type;

class EventEdge {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if ( null === self::$instance ) {
			self::$instance = new ObjectType(
				array(
					'name'   => 'EventEdge',
					'fields' => fn() => array(
						'cursor' => array(
							'type' => Type::nonNull( Type::string() ),
						),
						'node'   => array(
							'type' => Type::nonNull( EventType::get() ),
						),
					),
				)
			);
		}
		return self::$instance;
	}
}
