<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Interfaces;

use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Scalars\DateTime as DateTimeType;
use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Output\Event as EventType;
use Automattic\WooCommerceSimpleEvents\Internal\Api\Autogenerated\GraphQLTypes\Output\Session as SessionType;
use Automattic\WooCommerce\Api\Infrastructure\Schema\InterfaceType;
use Automattic\WooCommerce\Api\Infrastructure\Schema\Type;

class ScheduledItem {
	private static ?InterfaceType $instance = null;

	public static function get(): InterfaceType {
		if ( null === self::$instance ) {
			self::$instance = new InterfaceType(
				array(
					'name'        => 'ScheduledItem',
					'description' => __( 'An object with an id that occurs at a specific date and time.', 'woocommerce' ),
					'fields'      => fn() => array(
						'id'   => array(
							'type'        => Type::nonNull( Type::int() ),
							'description' => __( 'Numeric identifier.', 'woocommerce' ),
						),
						'date' => array(
							'type'        => DateTimeType::get(),
							'description' => __( 'Date and time the item occurs, as an ISO 8601 string.', 'woocommerce' ),
						),
					),
					'resolveType' => function ( $value ) {
						$class = get_class( $value );
						$map = array(
							'Automattic\WooCommerceSimpleEvents\Api\Types\Event' => EventType::get(),
							'Automattic\WooCommerceSimpleEvents\Api\Types\Session' => SessionType::get(),
						);
						return $map[ $class ] ?? null;
					},
				)
			);
		}
		return self::$instance;
	}
}
